/******************** generated by xml-casa (v2) from utils.xml *********************
********************* e581fa84576fcfcd247fa38ed8148354 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <utils_forward.h>

#include <utils_cmpt.h>

using namespace std;

namespace casac {



}
