##################### generated by xml-casa (v2) from mstransformer.xml #############
##################### 805829d3443acfecfe57cff868b76a61 ##############################
from __future__ import absolute_import 
from .__casac__ import mstransformer as _mstransformer
from .platform import str_encode as _str_ec
from .platform import str_decode as _str_dc
from .platform import dict_encode as _dict_ec
from .platform import dict_decode as _dict_dc
from .platform import dict_encode as _quant_ec
from .platform import dict_decode as _quant_dc
from .platform import encode as _any_ec
from .platform import decode as _any_dc
from .typecheck import validator as _pc
from .coercetype import coerce as _coerce


class mstransformer:
    ### self
    def __init__(self, *args, **kwargs):
        """Create a {tt mstransformer} tool, and initialize some variables.
        """
        self._swigobj = kwargs.get('swig_object',None)
        if self._swigobj is None:
            self._swigobj = _mstransformer()

    def done(self):
        """
        """
        _done_result = self._swigobj.done()
        return _done_result

    def config(self, pars={ }):
        """
        """
        schema = {'pars': {'type': 'cDict'}}
        doc = {'pars': pars}
        assert _pc.validate(doc,schema), str(_pc.errors)
        _config_result = self._swigobj.config(_dict_ec(_pc.document['pars']))
        return _config_result

    def open(self):
        """It assumes that mt.config() was run before.
        """
        _open_result = self._swigobj.open()
        return _open_result

    def run(self):
        """Execute the tool and apply the transformations.
        """
        _run_result = _dict_dc(self._swigobj.run())
        return _run_result

    def mergespwtables(self, filenames=[  ]):
        """Merge the spw sub-tables of a list of subMSs.
        
        """
        schema = {'filenames': {'type': 'cStrVec', 'coerce': [_coerce.to_list,_coerce.to_strvec]}}
        doc = {'filenames': filenames}
        assert _pc.validate(doc,schema), str(_pc.errors)
        _mergespwtables_result = self._swigobj.mergespwtables([_str_ec(_x) for _x in _pc.document['filenames']])
        return _mergespwtables_result

