/******************** generated by xml-casa (v2) from synthesisimstore.xml **********
********************* ad7f52ee22006d49bc399d2801fb74d2 *****************************/
%module synthesisimstore
%include <casa_typemaps.i>
%feature("kwargs");
%feature("autodoc", "0");

%feature("docstring", "

Summary:
    Close the tool

--------------------------------------------------------------------------------
") done;

%exception {
   try {
      $action
      } catch (const casacore::AipsError &ae) {
         PyErr_SetString(PyExc_RuntimeError, ae.what());
	 //PyErr_Print();
         return NULL;
      }
}
%include "synthesisimstore_cmpt.h"

%{
#include <exception>
#include <synthesisimstore_cmpt.h>
%}

