/******************** generated by xml-casa (v2) from synthesisimager.xml ***********
********************* 31f256e80795a946d4bd76b14412671d *****************************/
%module synthesisimager
%include <casa_typemaps.i>
%feature("kwargs");
%feature("autodoc", "0");

%feature("docstring", "

Summary:
    Select data from one MS

Input Parameters:
    selpars                   All parameters that control selection within one MS

--------------------------------------------------------------------------------
") selectdata;

%feature("docstring", "

Summary:
    reselect the data to match image definition

--------------------------------------------------------------------------------
") tuneselectdata;

%feature("docstring", "

Summary:
    Define image coordinate systems FTMs

Input Parameters:
    impars                    All parameters that control image coordinate system definition
    gridpars                  All parameters that control ftmachines and gridding parameters

--------------------------------------------------------------------------------
") defineimage;

%feature("docstring", "

Summary:
    Select data from one MS via conventional parameters (in lieu of selectdata)

Description:


Select data from one MS. Call this function in succession if there are
multiple MSs.

Input Parameters:
    msname                    Name of one measurement set
    spw                       Spectral Window / Channel / Frequency selection
    freqbeg                   Starting frequency/velocity/channel as a string with units. If spw is also supplied, the intersection will be used
    freqend                   End frequency/velocity/channel as a string with units.
    freqframe                 Frequency frame in which freqbeg and freqend are specified.
    field                     Field selection
    antenna                   Antenna / Baseline selection
    timestr                   Time range selection
    scan                      Scan selection
    obs                       Observation id selection
    state                     Scan Intent or State selection
    uvdist                    UV range selection
    taql                      Generic taql selection
    usescratch                Use scratch column (True) or virtual records (False) for model data
    readonly                  Open the MS in readonly mode. No model data will be written.
    incrmodel                 Subtract existing model data and start with residuals

--------------------------------------------------------------------------------
") setdata;

%feature("docstring", "

Summary:
    Define the image coordinate systems and types via conventinal parameters in lieu of defineimage

Description:


Define the image coordinate systems and shapes.

Input Parameters:
    imagename                 Base image name
    nx                        Total number of spatial pixels in x
    ny                        Total number of spatial pixels in y
    cellx                     Cellsize in x (e.g. '1arcsec')
    celly                     Cellsize in y (e.g. '1arcsec')
    stokes                    Stokes parameters to image (e.g. 'IQUV')
    phasecenter               Direction of phase center as a diretion measure or a field id 
    nchan                     Number of channels; a -1 (default) means all the channels as selected in selectvis and combined into one continuum channel 
    freqstart                 Start channel; A 0-relative channel number of the spwid  or a frequency quantity      or a velocity quantity or radial velocity measure
    freqstep                  Step in channel; integer for number of channels or frequency quantity or velocity quantity or radial velocity measure
    restfreq                  rest frequency to use; default => use the one available in ms 
    facets                    Number of facets on each axis
    ftmachine                 FT-Machine type
    ntaylorterms              Number of terms for a spectral Taylor expansion
    reffreq                   Reference Frequency of the image. Also used in the Taylor expansion.
    projection                Image coordinate system projection
    distance                  Distance to object: usually ignore this! (m)
    freqframe                 Frequency frame in which freqstart and freqstep are specified.
    tracksource               Track a source.
    trackdir                  Name of moving source, e.g planet or moon, to keep fixed in image
    overwrite                 Overwrite the image if it exists (true)
    padding                   FFT padding
    useautocorr               Use auto correlations
    usedoubleprec             Double Precision gridding or not
    wprojplanes               Number of w-projection planes
    convfunc                  Name of convolution function
    startmodel                Starting model ( image name or component list name )
    aterm                     Double Precision gridding or not
    psterm                    Double Precision gridding or not
    mterm                     Double Precision gridding or not
    wbawp                     Double Precision gridding or not
    cfcache                   Name of convolution function
    dopointing                Double Precision gridding or not
    dopbcorr                  Double Precision gridding or not
    conjbeams                 Double Precision gridding or not
    computepastep             Double Precision gridding or not
    rotatepastep              Double Precision gridding or not

--------------------------------------------------------------------------------
") setimage;

%feature("docstring", "

Summary:
    Set parameters to control weighting during imaging

Input Parameters:
    type                      Data weighting scheme
    rmode                     rmode
    noise                     Noise level
    robust                    Robustness weighting factor
    fieldofview               Field of view
    npixels                   NPixels
    multifield                Multifield
    uvtaper                   Parameters of uv-taper Gaussian

--------------------------------------------------------------------------------
") setweighting;

%feature("docstring", "

Summary:
    Make the psf

--------------------------------------------------------------------------------
") makepsf;

%feature("docstring", "

Summary:
    Predict model visibilities.

--------------------------------------------------------------------------------
") predictmodel;

%feature("docstring", "

Summary:
    Run a dry gridding run.

Description:




Input Parameters:
    cflist                     List of CFs 

--------------------------------------------------------------------------------
") drygridding;

%feature("docstring", "

Summary:
     Fill a potentially blank CFCache held inside the AWProject-class FTMachines. 

Description:




Input Parameters:
    cflist                     List of CFs 
    ftmname                    Name of the FTMachine used 
    cfcpath                    Path to the CFCache on the disk 
    pstermon                   Is the PS-term ON? 
    atermon                    Is the A-term ON? 
    conjbeams                  Use WB A-Projection algorithm (use frequency-conjugate beams)? 

--------------------------------------------------------------------------------
") fillcfcache;

%feature("docstring", "

Summary:
     Re-load the CFCache, the name of which should already be set in the tool. 

Description:




--------------------------------------------------------------------------------
") reloadcfcache;

%feature("docstring", "

Summary:
    Run a major cycle

Input Parameters:
    controls                  All parameters that control major cycle

--------------------------------------------------------------------------------
") executemajorcycle;

%feature("docstring", "

Summary:
    Make the primary beam

--------------------------------------------------------------------------------
") makepb;

%feature("docstring", "

Summary:
    Make the single-dish image

--------------------------------------------------------------------------------
") makesdimage;

%feature("docstring", "

Summary:
    Make the single-dish PSF

--------------------------------------------------------------------------------
") makesdpsf;

%feature("docstring", "

Summary:
    Get Image Store

Input Parameters:
    id                        Image field id

--------------------------------------------------------------------------------
") getimstore;

%feature("docstring", "

Summary:
    get internally stored coordsys record

--------------------------------------------------------------------------------
") getcsys;

%feature("docstring", "

Summary:
    get internally stored updated nchan

--------------------------------------------------------------------------------
") updatenchan;

%feature("docstring", "

Summary:
    Save natural gridded wt to disk.

--------------------------------------------------------------------------------
") getweightdensity;

%feature("docstring", "

Summary:
    Read in natural gridded wt from disk.

--------------------------------------------------------------------------------
") setweightdensity;

%feature("docstring", "

Summary:
    Close the tool

--------------------------------------------------------------------------------
") done;

%exception {
   try {
      $action
      } catch (const casacore::AipsError &ae) {
         PyErr_SetString(PyExc_RuntimeError, ae.what());
	 //PyErr_Print();
         return NULL;
      }
}
%include "synthesisimager_cmpt.h"

%{
#include <exception>
#include <synthesisimager_cmpt.h>
%}

