/******************** generated by xml-casa (v2) from utils.xml *********************
********************* 1cf6407697ca1942b37e37ea830645c3 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <utils_forward.h>

#include <utils_cmpt.h>

using namespace std;

namespace casac {



}
