/******************** generated by xml-casa (v2) from msmetadata.xml ****************
********************* 491dc4b6211db479fbb64db740378155 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <msmetadata_forward.h>

#include <msmetadata_cmpt.h>

using namespace std;

namespace casac {



}
