#ifndef _IMAGER_XML_IMAGER_CMPT_
#define _IMAGER_XML_IMAGER_CMPT_
/******************** generated by xml-casa (v2) from imager.xml ********************
********************* c03b7b3dd4848b112482640915bfc9bd *****************************/

#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <casa/Exceptions/Error.h>
#include <imager_forward.h>


using namespace std;

namespace casac {

  class  imager  {
    public:

      imager();
      bool advise(bool _takeadvice=bool(true), double _amplitudeloss=double(0.05), const variant& _fieldofview=variant( ), long& _pixels=_pixels_advise, record& _cell=_cell_advise, long& _facets=_facets_advise, string& _phasecenter=_phasecenter_advise);
      record* advisechansel(double _freqstart=double(1.0e6), double _freqend=double(1.1e6), double _freqstep=double(100.0), const string& _freqframe=string("LSRK"), const string& _msname=string(""), long _fieldid=long(0), bool _getfreqrange=bool(false), const string& _spwselection=string(""));
      bool approximatepsf(const string& _psf=string(""));
      bool boxmask(const string& _mask=string(""), const std::vector<long>& _blc=std::vector<long>({0,0,0,0}), const std::vector<long>& _trc=std::vector<long>({}), double _value=double(1.0));
      bool calcuvw(const std::vector<long>& _fields=std::vector<long>({-1}), const string& _refcode=string(""), bool _reuse=bool(true));
      record* clean(const string& _algorithm=string("clark"), long _niter=long(1000), double _gain=double(0.1), const variant& _threshold=variant( ), bool _displayprogress=bool(false), const std::vector<std::string>& _model=std::vector<std::string>({}), const std::vector<bool>& _keepfixed=std::vector<bool>({false}), const string& _complist=string(""), const std::vector<std::string>& _mask=std::vector<std::string>({}), const std::vector<std::string>& _image=std::vector<std::string>({}), const std::vector<std::string>& _residual=std::vector<std::string>({}), const std::vector<std::string>& _psfimage=std::vector<std::string>({}), bool _interactive=bool(false), long _npercycle=long(100), const string& _masktemplate=string(""));
      bool clipimage(const string& _image=string(""), const variant& _threshold=variant( ));
      bool clipvis(const variant& _threshold=variant( ));
      bool close();
      bool defineimage(long _nx=long(128), long _ny=long(-1), const variant& _cellx=variant( ), const variant& _celly=variant( ), const string& _stokes=string("I"), const variant& _phasecenter=variant( ), const string& _mode=string("mfs"), long _nchan=long(-1), const variant& _start=variant( ), const variant& _step=variant( ), const std::vector<long>& _spw=std::vector<long>({0}), const variant& _restfreq=variant( ), const string& _outframe=string("LSRK"), const string& _veltype=string("radio"), long _facets=long(1), const variant& _movingsource=variant( ), const variant& _distance=variant( ), const string& _projection=string("SIN"));
      bool done();
      record* drawmask(const string& _image=string(""), const string& _mask=string(""), long _niter=long(0), long _npercycle=long(0), const string& _threshold=string("0 mJy"));
      bool exprmask(const string& _mask=string(""), double _expr=double(1.0));
      bool feather(const string& _image=string(""), const string& _highres=string(""), const string& _lowres=string(""), const string& _lowpsf=string(""), double _effdishdiam=double(-1.0), bool _lowpassfiltersd=bool(false));
      bool filter(const string& _type=string("gaussian"), const variant& _bmaj=variant( ), const variant& _bmin=variant( ), const variant& _bpa=variant( ));
      bool fitpsf(const string& _psf=string(""), record& _bmaj=_bmaj_fitpsf, record& _bmin=_bmin_fitpsf, record& _bpa=_bpa_fitpsf);
      bool fixvis(const std::vector<long>& _fields=std::vector<long>({-1}), const std::vector<std::string>& _phasedirs=std::vector<std::string>({}), const string& _refcode=string(""), const std::vector<double>& _distances=std::vector<double>({0.0}), const string& _datacolumn=string("all"));
      bool ft(const std::vector<std::string>& _model=std::vector<std::string>({}), const string& _complist=string(""), bool _incremental=bool(false), double _phasecentertime=double(-1.0));
      variant* getweightgrid(const string& _type=string("imaging"), const std::vector<std::string>& _wgtimages=std::vector<std::string>({}));
      bool linearmosaic(const std::vector<std::string>& _images=std::vector<std::string>({}), const string& _mosaic=string(""), const string& _fluxscale=string(""), const string& _sensitivity=string(""), const std::vector<long>& _fieldids=std::vector<long>({0}), bool _usedefaultvp=bool(true), const string& _vptable=string(""));
      bool make(const string& _image=string(""));
      string predictcomp(const string& _objname=string(""), const string& _standard=string(""), const variant& _epoch=variant( ), const std::vector<double>& _freqs=std::vector<double>({1.0e11}), const string& _pfx=string("predictcomp"));
      bool makeimage(const string& _type=string("observed"), const string& _image=string(""), const string& _compleximage=string(""), bool _verbose=bool(true));
      bool makemodelfromsd(const string& _sdimage=string(""), const string& _modelimage=string(""), const string& _sdpsf=string(""), const string& _maskimage=string(""));
      bool mask(const string& _image=string(""), const string& _mask=string(""), const variant& _threshold=variant( ));
      bool mem(const string& _algorithm=string("entropy"), long _niter=long(20), const variant& _sigma=variant( ), const variant& _targetflux=variant( ), bool _constrainflux=bool(false), bool _displayprogress=bool(false), const std::vector<std::string>& _model=std::vector<std::string>({}), const std::vector<bool>& _keepfixed=std::vector<bool>({false}), const string& _complist=string(""), const std::vector<std::string>& _prior=std::vector<std::string>({}), const std::vector<std::string>& _mask=std::vector<std::string>({}), const std::vector<std::string>& _image=std::vector<std::string>({}), const std::vector<std::string>& _residual=std::vector<std::string>({}));
      bool nnls(const std::vector<std::string>& _model=std::vector<std::string>({}), const std::vector<bool>& _keepfixed=std::vector<bool>({false}), const string& _complist=string(""), long _niter=long(0), double _tolerance=double(1e-06), const std::vector<std::string>& _fluxmask=std::vector<std::string>({}), const std::vector<std::string>& _datamask=std::vector<std::string>({}), const std::vector<std::string>& _image=std::vector<std::string>({}), const std::vector<std::string>& _residual=std::vector<std::string>({}));
      bool open(const string& _thems=string(""), bool _compress=bool(false), bool _usescratch=bool(false));
      bool pb(const string& _inimage=string(""), const string& _outimage=string(""), const string& _incomps=string(""), const string& _outcomps=string(""), const string& _operation=string("apply"), const variant& _pointingcenter=variant( ), const variant& _parangle=variant( ), const string& _pborvp=string("pb"));
      bool plotsummary();
      bool plotuv(bool _rotate=bool(false));
      bool plotvis(const string& _type=string("all"), long _increment=long(1));
      bool plotweights(bool _gridded=bool(false), long _increment=long(1));
      bool regionmask(const string& _mask=string(""), const record& _region=initialize_record(""), const variant& _boxes=variant( ), const variant& _circles=variant( ), double _value=double(1.0));
      bool regiontoimagemask(const string& _mask=string(""), const record& _region=initialize_record(""), const variant& _boxes=variant( ), const variant& _circles=variant( ), double _value=double(1.0));
      bool residual(const std::vector<std::string>& _model=std::vector<std::string>({}), const string& _complist=string(""), const std::vector<std::string>& _image=std::vector<std::string>({}));
      bool restore(const std::vector<std::string>& _model=std::vector<std::string>({}), const string& _complist=string(""), const std::vector<std::string>& _image=std::vector<std::string>({}), const std::vector<std::string>& _residual=std::vector<std::string>({}));
      bool updateresidual(const std::vector<std::string>& _model=std::vector<std::string>({}), const string& _complist=string(""), const std::vector<std::string>& _image=std::vector<std::string>({}), const std::vector<std::string>& _residual=std::vector<std::string>({}));
      bool sensitivity(record& _pointsource=_pointsource_sensitivity, double& _relative=_relative_sensitivity, double& _sumweights=_sumweights_sensitivity, record& _senrec=_senrec_sensitivity);
      bool apparentsens(double& _pointsource=_pointsource_apparentsens, double& _relative=_relative_apparentsens);
      bool setbeam(const variant& _bmaj=variant( ), const variant& _bmin=variant( ), const variant& _bpa=variant( ));
      bool selectvis(const string& _vis=string(""), const std::vector<long>& _nchan=std::vector<long>({-1}), const std::vector<long>& _start=std::vector<long>({0}), const std::vector<long>& _step=std::vector<long>({1}), const variant& _spw=variant( ), const variant& _field=variant( ), const variant& _baseline=variant( ), const variant& _time=variant( ), const variant& _scan=variant( ), const string& _intent=string(""), const variant& _observation=variant( ), const variant& _uvrange=variant( ), const string& _taql=string(""), bool _usescratch=bool(false), bool _datainmemory=bool(false), bool _writeaccess=bool(true));
      record* setjy(const variant& _field=variant( ), const variant& _spw=variant( ), const string& _modimage=string(""), const std::vector<double>& _fluxdensity=std::vector<double>({0.0,0.0,0.0,0.0}), const string& _standard=string("SOURCE"), bool _scalebychan=bool(false), const std::vector<double>& _spix=std::vector<double>({0.0}), const variant& _reffreq=variant( ), const std::vector<double>& _polindex=std::vector<double>({0.0}), const std::vector<double>& _polangle=std::vector<double>({0.0}), double _rotmeas=double(0.0), const string& _time=string(""), const string& _scan=string(""), const string& _intent=string(""), const string& _observation=string(""), const string& _interpolation=string("nearest"));
      bool ssoflux();
      bool setmfcontrol(double _cyclefactor=double(1.5), double _cyclespeedup=double(-1), double _cyclemaxpsffraction=double(0.8), long _stoplargenegatives=long(2), long _stoppointmode=long(-1), double _minpb=double(0.1), const string& _scaletype=string("NONE"), double _constpb=double(0.4), const std::vector<std::string>& _fluxscale=std::vector<std::string>({}), bool _flatnoise=bool(true));
      bool setoptions(const string& _ftmachine=string("ft"), long _cache=long(-1), long _tile=long(16), const string& _gridfunction=string("SF"), const variant& _location=variant( ), double _padding=double(1.0), const string& _freqinterp=string("nearest"), long _wprojplanes=long(-1), const string& _epjtablename=string(""), bool _applypointingoffsets=bool(false), bool _dopbgriddingcorrections=bool(true), const string& _cfcachedirname=string(""), double _rotpastep=double(5.0), double _pastep=double(360.0), double _pblimit=double(0.05), long _imagetilevol=long(0), bool _singleprecisiononly=bool(false), long _numthreads=long(-1), bool _psterm=bool(true), bool _aterm=bool(true), bool _mterm=bool(true), bool _wbawp=bool(false), bool _conjbeams=bool(true));
      bool setscales(const string& _scalemethod=string("nscales"), long _nscales=long(5), const std::vector<double>& _uservector=std::vector<double>({0.0,3.0,10.0}));
      bool setsmallscalebias(float _inbias=float(0.6));
      bool settaylorterms(long _ntaylorterms=long(2), double _reffreq=double(0.0));
      bool setsdoptions(double _scale=double(1.0), double _weight=double(1.0), long _convsupport=long(-1), const string& _pointingcolumntouse=string("DIRECTION"), const variant& _truncate=variant( ), const variant& _gwidth=variant( ), const variant& _jwidth=variant( ), double _minweight=double(0.), bool _clipminmax=bool(false));
      bool setvp(bool _dovp=bool(false), bool _usedefaultvp=bool(true), const string& _vptable=string(""), bool _dosquint=bool(false), const variant& _parangleinc=variant( ), const variant& _skyposthreshold=variant( ), const string& _telescope=string(""), bool _verbose=bool(true));
      bool setweightgrid(const variant& _weight=variant( ), const string& _type=string("imaging"));
      bool smooth(const std::vector<std::string>& _model=std::vector<std::string>({}), const std::vector<std::string>& _image=std::vector<std::string>({}), bool _usefit=bool(true), const variant& _bmaj=variant( ), const variant& _bmin=variant( ), const variant& _bpa=variant( ), bool _normalize=bool(true));
      bool stop();
      bool summary();
      bool uvrange(double _uvmin=double(0.0), double _uvmax=double(0.0));
      bool weight(const string& _type=string("natural"), const string& _rmode=string("none"), const variant& _noise=variant( ), double _robust=double(0.0), const variant& _fieldofview=variant( ), long _npixels=long(0), bool _mosaic=bool(false));
      record* mapextent(const string& _ref=string("J2000"), const string& _movingsource=string(""), const string& _pointingcolumntouse=string("DIRECTION"));
      record* pointingsampling(const string& _pattern=string("raster"), const string& _ref=string("J2000"), const string& _movingsource=string(""), const string& _pointingcolumntouse=string("DIRECTION"), const string& _antenna=string(""));

        ~imager( );

    private:

#include <imager_private.h>


      // --- declarations of static parameter defaults ---
    public:
      static long _pixels_advise;
      static record _cell_advise;
      static long _facets_advise;
      static string _phasecenter_advise;
      static record _bmaj_fitpsf;
      static record _bmin_fitpsf;
      static record _bpa_fitpsf;
      static record _pointsource_sensitivity;
      static double _relative_sensitivity;
      static double _sumweights_sensitivity;
      static record _senrec_sensitivity;
      static double _pointsource_apparentsens;
      static double _relative_apparentsens;
  };

}

#endif
