/******************** generated by xml-casa (v2) from coordsys.xml ******************
********************* ba72f6b892d295fcf5df093fb446253b *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <coordsys_forward.h>

#include <coordsys_cmpt.h>

using namespace std;

namespace casac {



}
