/******************** generated by xml-casa (v2) from functional.xml ****************
********************* 0f13b59a4d4f695c2b3330fbedc6740d *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <functional_forward.h>

#include <functional_cmpt.h>

using namespace std;

namespace casac {



}
