/******************** generated by xml-casa (v2) from imagepol.xml ******************
********************* 4853322d6c42c34a089bf0abdce51773 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <imagepol_forward.h>

#include <image_cmpt.h>

#include <imagepol_cmpt.h>

using namespace std;

namespace casac {



}
