/******************** generated by xml-casa (v2) from imagemetadata.xml *************
********************* a6949a9b048f9c174974cdafb7d2b5c3 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <imagemetadata_forward.h>

#include <imagemetadata_cmpt.h>

using namespace std;

namespace casac {



}
