/******************** generated by xml-casa (v2) from image.xml *********************
********************* 43c366e8efb8bfc2fac6601bf7eb47d3 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <image_forward.h>

#include <coordsys_cmpt.h>

#include <componentlist_cmpt.h>

#include <image_cmpt.h>

using namespace std;

namespace casac {



}
