/******************** generated by xml-casa (v2) from imagepol.xml ******************
********************* 3b7437629b45930681a8977ca52048f2 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <imagepol_forward.h>

#include <image_cmpt.h>

#include <imagepol_cmpt.h>

using namespace std;

namespace casac {



}
