/******************** generated by xml-casa (v2) from logsink.xml *******************
********************* 2c61a1398d9ef908298f9bf297e60b85 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <logsink_forward.h>

#include <logsink_cmpt.h>

using namespace std;

namespace casac {



}
