/******************** generated by xml-casa (v2) from measures.xml ******************
********************* c6df19b0ab10f5240b76f86ae90e951a *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <measures_forward.h>

#include <measures_cmpt.h>

using namespace std;

namespace casac {

  record measures::_dot_touvw=initialize_record("""");
  record measures::_xyz_touvw=initialize_record("""");
  record measures::_xyz_expand=initialize_record("""");

}
