/******************** generated by xml-casa (v2) from ms.xml ************************
********************* 39a3c11106700d068d59e7f714f10974 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <ms_forward.h>

#include <table_cmpt.h>

#include <msmetadata_cmpt.h>

#include <ms_cmpt.h>

using namespace std;

namespace casac {



}
