/******************** generated by xml-casa (v2) from ms.xml ************************
********************* 0c0b2949bc733c31a2ea749782aec042 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <ms_forward.h>

#include <table_cmpt.h>

#include <msmetadata_cmpt.h>

#include <ms_cmpt.h>

using namespace std;

namespace casac {



}
