/******************** generated by xml-casa (v2) from ms.xml ************************
********************* edbee3a0bea27927d5404fdf882bca1f *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <ms_forward.h>

#include <table_cmpt.h>

#include <msmetadata_cmpt.h>

#include <ms_cmpt.h>

using namespace std;

namespace casac {



}
