/******************** generated by xml-casa (v2) from msmetadata.xml ****************
********************* 4fe5a0df6777f7f941decb397b1da92f *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <msmetadata_forward.h>

#include <msmetadata_cmpt.h>

using namespace std;

namespace casac {



}
