/******************** generated by xml-casa (v2) from quanta.xml ********************
********************* 18150fd18af6d56f92e5cf7a8abb1e3d *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <quanta_forward.h>

#include <quanta_cmpt.h>

using namespace std;

namespace casac {



}
