/******************** generated by xml-casa (v2) from regionmanager.xml *************
********************* 4ff09691e40ce125872be37332fdf213 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <regionmanager_forward.h>

#include <regionmanager_cmpt.h>

using namespace std;

namespace casac {



}
