/******************** generated by xml-casa (v2) from synthesisimager.xml ***********
********************* da1df46ab2bd48dc68926d1aead7d67f *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <synthesisimager_forward.h>

#include <synthesisimstore_cmpt.h>

#include <synthesisimager_cmpt.h>

using namespace std;

namespace casac {



}
