#!/usr/bin/perl

open( $gitver, "git tag -l '[0-9]*.[0-9]*.[0-9]*' 2> /dev/null |" );
chomp( @versions = <$gitver> );
close( $gitver );
@versions = grep(/^\d+.\d+.\d+$/, @versions);
sort @versions;
print( $versions[$#versions], "\n" );
