#!/usr/bin/perl
$gitbranch=`git branch | grep "\*" | cut -d ' ' -f2`;
chomp($gitbranch);
#print ($gitbranch."\n");
open( $githashes, "git log --simplify-by-decoration --pretty='%H' ".$gitbranch." |" );
chomp( @hashes = <$githashes> );
close( $githashes );
@versions;
foreach ( @hashes ) {
	#print "$_\n";
    open( $gitver, "git show-ref --tags -d | grep ^" . $_ . " | sed -e 's,.* refs/tags/,,' | sed -e 's/\\^{}//' 2> /dev/null |" );
    chomp( @tags = <$gitver> );
    #print ( $tags[$#tags], "\n" );
    push @versions, @tags;
    close( $gitver );
}
#print ($versions);
@versions = grep(/^\d+\.\d+\.\d+\.\d+$/, @versions);
#https://rosettacode.org/wiki/Sort_a_list_of_object_identifiers#Python
my @sorted =
    map { $_->[0] }
    sort { $a->[1] cmp $b->[1] }
    map { [$_, join '', map { sprintf "%8d", $_ } split /\./, $_] }
    @versions;

#print ("@sorted\n");
print( $sorted[$#sorted], "\n" );
