#ifndef _ATMOSPHERE_XML_ATMOSPHERE_CMPT_
#define _ATMOSPHERE_XML_ATMOSPHERE_CMPT_
/******************** generated by xml-casa (v2) from atmosphere.xml ****************
********************* e79b0bbe7303e5be53ed0d1656b65f07 *****************************/

#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <casa/Exceptions/Error.h>
#include <atmosphere_forward.h>


using namespace std;

namespace casac {

  class  atmosphere  {
    public:

      atmosphere();
      bool close();
      bool done();
      string getAtmVersion();
      std::vector<std::string> listAtmosphereTypes();
      string initAtmProfile(const Quantity& _altitude=Quantity(std::vector<double>(1,5000.),"m"), const Quantity& _temperature=Quantity(std::vector<double>(1,270.0),"K"), const Quantity& _pressure=Quantity(std::vector<double>(1,560.0),"mbar"), const Quantity& _maxAltitude=Quantity(std::vector<double>(1,48.0),"km"), double _humidity=double(20.0), const Quantity& _dTem_dh=Quantity(std::vector<double>(1,-5.6),"K/km"), const Quantity& _dP=Quantity(std::vector<double>(1,10.0),"mbar"), double _dPm=double(1.2), const Quantity& _h0=Quantity(std::vector<double>(1,2.0),"km"), int _atmType=int(1), const std::vector<double>& _layerBoundaries=std::vector<double>({}), const std::vector<double>& _layerTemperature=std::vector<double>({}));
      string updateAtmProfile(const Quantity& _altitude=Quantity(std::vector<double>(1,5000.),"m"), const Quantity& _temperature=Quantity(std::vector<double>(1,270.0),"K"), const Quantity& _pressure=Quantity(std::vector<double>(1,560.0),"mbar"), double _humidity=double(20.0), const Quantity& _dTem_dh=Quantity(std::vector<double>(1,-5.6),"K/km"), const Quantity& _h0=Quantity(std::vector<double>(1,2.0),"km"));
      string getBasicAtmParms(Quantity& _altitude=_altitude_getBasicAtmParms, Quantity& _temperature=_temperature_getBasicAtmParms, Quantity& _pressure=_pressure_getBasicAtmParms, Quantity& _maxAltitude=_maxAltitude_getBasicAtmParms, double& _humidity=_humidity_getBasicAtmParms, Quantity& _dTem_dh=_dTem_dh_getBasicAtmParms, Quantity& _dP=_dP_getBasicAtmParms, double& _dPm=_dPm_getBasicAtmParms, Quantity& _h0=_h0_getBasicAtmParms, string& _atmType=_atmType_getBasicAtmParms);
      int getNumLayers();
      Quantity getGroundWH2O();
      string getProfile(Quantity& _thickness=_thickness_getProfile, Quantity& _temperature=_temperature_getProfile, Quantity& _watermassdensity=_watermassdensity_getProfile, Quantity& _water=_water_getProfile, Quantity& _pressure=_pressure_getProfile, Quantity& _O3=_O3_getProfile, Quantity& _CO=_CO_getProfile, Quantity& _N2O=_N2O_getProfile);
      int initSpectralWindow(int _nbands=int(1), const Quantity& _fCenter=Quantity(std::vector<double>(1,90),"GHz"), const Quantity& _fWidth=Quantity(std::vector<double>(1,0.64),"GHz"), const Quantity& _fRes=Quantity(std::vector<double>(1,0.0),"GHz"));
      int addSpectralWindow(const Quantity& _fCenter=Quantity(std::vector<double>(1,350),"GHz"), const Quantity& _fWidth=Quantity(std::vector<double>(1,0.008),"GHz"), const Quantity& _fRes=Quantity(std::vector<double>(1,0.002),"GHz"));
      int getNumSpectralWindows();
      int getNumChan(int _spwid=int(0));
      int getRefChan(int _spwid=int(0));
      Quantity getRefFreq(int _spwid=int(0));
      Quantity getChanSep(int _spwid=int(0));
      Quantity getChanFreq(int _chanNum=int(0), int _spwid=int(0));
      Quantity getSpectralWindow(int _spwid=int(0));
      double getChanNum(const Quantity& _freq=Quantity(std::vector<double>(1,0.0),"GHz"), int _spwid=int(0));
      Quantity getBandwidth(int _spwid=int(0));
      Quantity getMinFreq(int _spwid=int(0));
      Quantity getMaxFreq(int _spwid=int(0));
      double getDryOpacity(int _nc=int(-1), int _spwid=int(0));
      double getDryContOpacity(int _nc=int(-1), int _spwid=int(0));
      double getO2LinesOpacity(int _nc=int(-1), int _spwid=int(0));
      double getO3LinesOpacity(int _nc=int(-1), int _spwid=int(0));
      double getCOLinesOpacity(int _nc=int(-1), int _spwid=int(0));
      double getN2OLinesOpacity(int _nc=int(-1), int _spwid=int(0));
      Quantity getWetOpacity(int _nc=int(-1), int _spwid=int(0));
      double getH2OLinesOpacity(int _nc=int(-1), int _spwid=int(0));
      double getH2OContOpacity(int _nc=int(-1), int _spwid=int(0));
      int getDryOpacitySpec(int _spwid=int(0), std::vector<double>& _dryOpacity=_dryOpacity_getDryOpacitySpec);
      int getWetOpacitySpec(int _spwid=int(0), Quantity& _wetOpacity=_wetOpacity_getWetOpacitySpec);
      Quantity getDispersivePhaseDelay(int _nc=int(-1), int _spwid=int(0));
      Quantity getDispersiveWetPhaseDelay(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersiveWetPhaseDelay(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersiveDryPhaseDelay(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersivePhaseDelay(int _nc=int(-1), int _spwid=int(0));
      Quantity getDispersivePathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getDispersiveWetPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersiveWetPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersiveDryPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getO2LinesPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getO3LinesPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getCOLinesPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getN2OLinesPathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getNonDispersivePathLength(int _nc=int(-1), int _spwid=int(0));
      Quantity getAbsH2OLines(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsH2OCont(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsO2Lines(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsDryCont(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsO3Lines(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsCOLines(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsN2OLines(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsTotalDry(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      Quantity getAbsTotalWet(int _nl=int(0), int _nf=int(0), int _spwid=int(0));
      bool setUserWH2O(const Quantity& _wh2o=Quantity(std::vector<double>(1,0.0),"mm"));
      Quantity getUserWH2O();
      bool setAirMass(double _airmass=double(0.0));
      double getAirMass();
      bool setSkyBackgroundTemperature(const Quantity& _tbgr=Quantity(std::vector<double>(1,2.73),"K"));
      Quantity getSkyBackgroundTemperature();
      Quantity getAverageTebbSky(int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"));
      Quantity getTebbSky(int _nc=int(-1), int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"));
      int getTebbSkySpec(int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"), Quantity& _tebbSky=_tebbSky_getTebbSkySpec);
      Quantity getAverageTrjSky(int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"));
      Quantity getTrjSky(int _nc=int(-1), int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"));
      int getTrjSkySpec(int _spwid=int(0), const Quantity& _wh2o=Quantity(std::vector<double>(1,-1),"mm"), Quantity& _trjSky=_trjSky_getTrjSkySpec);

        ~atmosphere( );

    private:

#include <atmosphere_private.h>


      // --- declarations of static parameter defaults ---
    public:
      static Quantity _altitude_getBasicAtmParms;
      static Quantity _temperature_getBasicAtmParms;
      static Quantity _pressure_getBasicAtmParms;
      static Quantity _maxAltitude_getBasicAtmParms;
      static double _humidity_getBasicAtmParms;
      static Quantity _dTem_dh_getBasicAtmParms;
      static Quantity _dP_getBasicAtmParms;
      static double _dPm_getBasicAtmParms;
      static Quantity _h0_getBasicAtmParms;
      static string _atmType_getBasicAtmParms;
      static Quantity _thickness_getProfile;
      static Quantity _temperature_getProfile;
      static Quantity _watermassdensity_getProfile;
      static Quantity _water_getProfile;
      static Quantity _pressure_getProfile;
      static Quantity _O3_getProfile;
      static Quantity _CO_getProfile;
      static Quantity _N2O_getProfile;
      static std::vector<double> _dryOpacity_getDryOpacitySpec;
      static Quantity _wetOpacity_getWetOpacitySpec;
      static Quantity _tebbSky_getTebbSkySpec;
      static Quantity _trjSky_getTrjSkySpec;
  };

}

#endif
