/******************** generated by xml-casa (v2) from coordsys.xml ******************
********************* 35f6dbcc87a1b64fb6cde84d1efb1911 *****************************/
#include <vector>
#include <string>
#include <complex>
#include <stdcasa/record.h>
#include <casaswig_types.h>
#include <coordsys_forward.h>

#include <coordsys_cmpt.h>

using namespace std;

namespace casac {



}
